version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Ruta para el build.gradle de la raíz
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/architectureComponentsApp/app" # Ruta para el build.gradle de un submódulo
    schedule:
      interval: "weekly"
