version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/architectureComponentsApp/app/" # Directorio raíz donde está el archivo build.gradle
    schedule:
      interval: "weekly" # Puedes cambiarlo a "daily", "monthly", etc.
