version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Directorio raíz donde está el archivo build.gradle
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "UpdatE Dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/app" # Subdirectorio donde está el build.gradle del submódulo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Update DependencieS"
    groups:
      all-dependencies:
        patterns:
          - "*"
