version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Raíz donde está el archivo build.gradle
    schedule:
      interval: "weekly" # O el intervalo que prefieras
    open-pull-requests-limit: 1
    commit-message:
      prefix: "MSO-TEST"
    groups:
      all-dependencies:
        patterns:
          - "*"
          - "app/*" # Agrega el subdirectorio de app también

  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "MSO-TEST"
    groups:
      all-dependencies:
        patterns:
          - "*"
