name: Android CI for Dependabot

on:
  pull_request:
    branches:
      - main  # O el branch principal que estés utilizando
    types:
      - opened
      - synchronize  # También se ejecuta cuando el PR se actualiza

jobs:
  build:
    if: github.actor == 'dependabot[bot]'  # Filtra para que solo se ejecute si el PR es de Dependabot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: '31.0.0'

      - name: Build app
        run: ./gradlew assembleDebug

      - name: Run tests
        run: ./gradlew test

      - name: Upload APK for testing
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
